### ISSUE TITLE
Draft page load issue

### ISSUE THREAD

**Issue by zubain** [rks92/LPC#2]
In app/controllers/league_controller.rb:51:in `draftPage'

Error thrown at line 51: 'if draftGlobals.picked_players == nil'

**Comment by zubain** [comment]
[ZS] Updates: Draft page loads when I create a new league after logic was implemented. Perhaps this is the way it's supposed to work. 
Can close the issue if behavior is confirmed by others too

**Comment by rks92** [comment]
Yes. We made changes to the tables. I can scrub the data if you need me to. But previous leagues will not work
